test_name: Check we can get to all nested routes

includes:
  - !include common.yaml

stages:
  - name: comments in posts
    request:
      url: "{host:s}/posts/1/comments"
      params:
        postId: 1
        id: 2
      method: GET
    response:
      status_code: 200
      body:
        - id: 2
  - name: albums per user
    request:
      url: "{host:s}/users/1/albums"
      params:
        albumId: 1
        id: 3
      method: GET
    response:
      status_code: 200
      body:
        - id: 3
  - name: todos per user
    request:
      url: "{host:s}/users/1/todos"
      params:
        userId: 1
        id: 4
      method: GET
    response:
      status_code: 200
      body:
        - id: 4
  - name: posts per user
    request:
      url: "{host:s}/users/1/posts"
      params:
        userId: 1
        id: 8
      method: GET
    response:
      status_code: 200
      body:
        - id: 8
  - name: photos in albums
    request:
      url: "{host:s}/albums/1/photos"
      params:
        albumId: 1
        id: 10
      method: GET
    response:
      status_code: 200
      body:
        - id: 10
